/* Copyright (C) 2022-2023 Ementor Romania - All Rights Reserved */
package com.ementor.profile.service.enums;

public enum SchoolSpecialityEnum {
	AGRICULTURE, ARCHITECTURE, ARCHITECTURE_AMBIENT_ARTS_AND_DESIGN, ACTOR_ART, PLASTIC_ARTS, PLASTIC_AND_DECORATIVE_ARTS, VISUAL_ARTS, LIBRARIAN_DOCUMENTALIST, INDUSTRIAL_CHEMISTRY, COMMERCE, CONSTRUCTION_INSTALLATIONS_AND_PUBLIC_WORKS, CHOREOGRAPHY, ECONOMIC, EDUCATOR, ELECTRIC, ELECTROMECHANICS, ELECTRONICS_AUTOMATIONS, AESTHETICS_AND_HUMAN_BODY_HYGIENE, WOOD_PRODUCTS_MANUFACTURING, PHILOLOGY, CATHOLIC_RELIGIOUS_TOURISM_GUIDE, ORTHODOX_RELIGIOUS_TOURISM_GUIDE, FOOD_INDUSTRY, TEXTILE_AND_LEATHER_INDUSTRY, EXTRASCHOOL_EDUCATION_INSTRUCTOR, MATHEMATICS_INFORMATICS, BUILDING_MATERIALS, PRODUCTION_MEDIA, ENVIRONMENT_PROTECTION, FORESTRY, SPORTS, NATURAL_SCIENCES, SOCIAL_SCIENCES, POLYGRAPHIC_TECHNIQUES, ADVENTIST_THEOLOGY, BAPTIST_THEOLOGY, GREEK_CATHOLIC_THEOLOGY, MUSLIM_THEOLOGY, ORTHODOX_THEOLOGY, PENTECOSTAL_THEOLOGY, REFORMED_THEOLOGY, ROMAN_CATHOLIC, THEOLOGY_UNITARIAN, THEOLOGY_REAL_SPEC_GERMAN_HUMAN, SPEC_GERMAN, TOURISM_AND_FOOD, WALDORF_PHILOLOGY
}
